server:
  port: 7003
eureka:
  instance:
    hostname: localhost  #Eureka服务端的名字
  client:
    registry-with-eureka : false #表示是否向eureka注册中心注册自己
    fetch-registry: false #为false则表示自己为注册中心
    service-url: #监控页面
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/