server:
  port: 9527
spring:
  application:
    name: springcloud-zull
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/，http://localhost:7003/eureka/
    instance:
      instance-id:  zull-9527.com
      prefer-ip-address: true    #隐藏真实地址
info:
  app.name: zsh.springcloud #项目名称
  company.name: zsh #公司名称

zuul:
  routes:
    mydept.serviceId: springcloud-provider-dept
    mydept.path: /mydept/**
    ignored-services: "*"  # 不能再使用这个路径访问了，ignored ： 忽略,隐藏全部的~
    prefix: /kuang # 设置公共的前缀