server:
  port: 8001
mybatis:
  type-aliases-package: com.zsh.springcloud.pojo
  config-location:  classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

spring:
  application:
    name: springcloud-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/db01?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root

#Eureka配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/，http://localhost:7003/eureka/
  instance:
    instance-id: springcloud-provide-dept8001 #修改Eureka上的默认描述信息

#info配置
info:
  app.name: zsh
  company.name: zjs
